v0.65

diff --git a/biosdisk b/biosdisk
--- a/biosdisk
+++ b/biosdisk
@@ -19,53 +19,56 @@
 # Purpose: This program can be used to quickly create a bootable DOS disk
 # with a BIOS flash executable file
 #
-# Last Update: Jul 19 2004
+# Last Update: 2004-11-12
 
-
-makedisk=0
-tmppath="/tmp/biosdisk"
-make_floppy_flag=0
-make_pkg_flag=0
-make_image_flag=1
-install_flag=0
-options=""
+baseDir="/usr/share/biosdisk"
+confFile="/etc/biosdisk.conf"
+tmpMount="/tmp/biosdisk"
+libDir="/var/lib/biosdisk"
+tmpPath="/tmp"
+curDir=`pwd`
 device="/dev/fd0"
-biosdisk_tree="/var/lib/biosdisk"
-tmp_location="/tmp"
-image_complete=0
-distro=""
-pkg_version=""
-pkg_release=""
-pkg_name=""
-force_flag=1
-dest_specified=0
+blconf="/usr/sbin/blconf"
+wget="/usr/bin/wget"
+options=""
 
-source /etc/biosdisk/biosdisk.conf
+# Flags
+mkDisk=0 # TODO:used?
+mkFloppyFlag=0
+mkPkgFlag=0
+mkImgFlag=1 #TODO: needed?
+installFlag=0
+imgCompleteFlag=0
+forceFlag=1
+destSpecifiedFlag=0
+
+if [ -e "$confFile" ]; then
+    source "$confFile"
+fi
 
 destination=""
-dosdisk=$biosdisk_tree/dosdisk.img
-specfile="/etc/biosdisk/biosdisk-mkrpm-template.spec"
-rpm_basedir="$biosdisk_tree/rpm"
-
-# TO DO
-#biosdisk pxeadd [-o option] /path/[rawbiosfile.exe|imagename.img]
-
+dosDisk="$baseDir/dosdisk.img"
+pkgSupported="Rpm, Dpkg"
+rpmBaseDir="$libDir/rpm"
+dpkgPath=""
+dpkgName=""
 
 ####################### Functions ########################
-function show_usage()
+function showUsage()
 {
-    echo $"Usage: $0 [action] [options] /path/filename[.img|.exe]"
-    echo $"  [action]  =  { mkfloppy | mkimage | mkpkg } "
+    echo $"Usage: $0 [action] [options] /path/fileName[.img|.exe]"
+    echo $"  [action]  =  { mkfloppy | mkimage | mkpkg | install | uninstall} "
     echo $"  [options] =  [-o option ] [-d device] [ -k basimage]"
     echo $"               [-i destination] [--install] [--distro=<distro>]"
     echo $"               [--name=<pkg name>] [--version=<pkg version>]"
-    echo $"               [--release=<pkg release>] [-h|--help]"
+    echo $"               [--release=<pkg release>] [--bioslog=<bios changelog>]"
+    echo $"               [-h|--help]"
 }
 
-function make_image()
+function makeImage()
 {
     # Protect against involuntary overwriting
-    if [ -e $destination ] && [ $force_flag == "0" ]; then
+    if [ -e $destination ] && [ $forceFlag == "0" ]; then
         echo "Warning: $destination already exists! [O]verwrite/[A]bort?"
         read choice
         loop=1
@@ -88,90 +91,189 @@ function make_image()
         done
     fi
     
-    mkdir -p $tmppath
-    cp -f $dosdisk $destination
-    mount -t vfat $destination $tmppath -o loop
-    cp -f $biosfile $tmppath
-    echo "$biosname $options" > $tmppath/autoexec.bat
-    cd $tmppath
-    unix2dos autoexec.bat > /dev/null 2>&1
-    cd -
-    umount $tmppath
-    rm -rf $tmppath
-                                                                                                                
-    if [ "$make_floppy_flag" == 1 ]; then
-        echo "Creating BIOS boot floppy on $device"
-        cat $destination > $device
-    elif [ "$make_pkg_flag" == 0 ]; then
-        echo "Creating BIOS floppy image at $destination"
+    mkdir -p $tmpMount
+    cp -f $dosDisk $destination
+    mount -t vfat $destination $tmpMount -o loop
+    cp -f $biosFile $tmpMount
+    echo "$biosName $options" > $tmpMount/autoexec.bat
+    unix2dos $tmpMount/autoexec.bat > /dev/null 2>&1
+    umount $tmpMount
+    rm -rf $tmpMount
+   
+    if ! [ "$uninstallFlag" == 1 ]; then
+        if [ "$mkFloppyFlag" == 1 ]; then
+            echo "Creating BIOS boot floppy on $device"
+            cat $destination > $device
+        elif [ "$mkPkgFlag" == 0 ]; then
+            echo "Creating BIOS floppy image at $destination"
+        fi
     fi
 }
 
-function setup_pxe()
+function setupPxe()
 {
     echo "Not yet supported"
     exit 1
 
 }
 
-function make_rpm()
+function makeDpkg()
 {
-    # Create base structure
-    mkdir -p $rpm_basedir
-    mkdir -p $rpm_basedir/BUILD
-    mkdir -p $rpm_basedir/SOURCES
-    mkdir -p $rpm_basedir/SPECS
-    mkdir -p $rpm_basedir/RPMS/noarch
-    mkdir -p $rpm_basedir/SRPMS
-
-    cp -f $destination $rpm_basedir/SOURCES
-    cp -f $specfile $rpm_basedir/SPECS
-
-    if [ -z "$pkg_name" ]; then
-        pkg_name=bios
+    # Test if build environment is sufficient/sane
+    if [ ! -f /usr/bin/dpkg ]; then
+	echo "Error: This cannot be a Debian system, you do not have dpkg installed!"
+	exit 1
     fi
-
-    if [ -z "$pkg_version" ]; then
-        pkg_version=$filename
+    dhStatus=`dpkg -s debhelper | grep "Status"`
+    if [ ! "$dhStatus" == 'Status: install ok installed' ]; then
+        echo "Error: debhelper does not seem to be installed correctly, please install via dpkg!"
+	exit 1
     fi
-
-    if [ -z "$pkg_release" ]; then
-        pkg_release=1
+    if [ -z "$pkgName" ]; then
+        pkgName=dellbios
     fi
-
-    rpmbuild --define "_topdir $rpm_basedir" --define "name $pkg_name" --define "version $pkg_version" --define "release $pkg_release" --define "destination $destination" -ba $rpm_basedir/SPECS/`basename $specfile` >/dev/null 2>&1
-
-    if [ "$?" -eq 0 ]; then
-        echo $""
-        echo $"Created $pkg_name-$pkg_version-$pkg_release.noarch.rpm in $rpm_basedir/RPMS/noarch/"
-        echo $""
-        echo $"biosdisk: mkrpm Completed."
+    if [ -z "$pkgVersion" ]; then
+        pkgVersion=`date +%Y%m%d`
+    fi
+    if [ -z "$pkgRelease" ]; then
+        pkgRelease=1
+    fi
+    if [ -z "$biosChangeLog" ]; then
+        biosChangeLog=""
+    fi
+    # pkgRelease treated as debian revision count
+    # current solution imitates a kernel/initrd pair, its suboptimal
+    if [ -e $destination ]; then
+	destDir=`dirname $destination`
+	dpkgPath="$destDir/$pkgName-$pkgVersion"
     else
-        echo $"Error! There was a problem creating your rpm."
-        exit 7
+        dpkgPath="$tmpPath/$pkgName-$pkgVersion"
+    fi
+    echo "Building Debian package in $dpkgPath ..."
+    dpkgName=$pkgName"_"$pkgVersion"-"$pkgRelease"_i386.deb"
+    # Redefining $destination, suboptimal
+    destination=$dpkgPath"/initrd.img-"$pkgVersion"-"$pkgName
+    # exporting variables so that make in debian/rules gets them
+    export pkgName pkgVersion pkgRelease dpkgPath biosChangeLog
+    if [ -e $dpkgPath ]; then
+        rm -rf $dpkgPath
+    fi
+    mkdir $dpkgPath
+    tar -x --bzip2 -f "$baseDir/dpkgfiles.tar.bz2" -C $dpkgPath
+    cd $dpkgPath
+    makeImage
+    debian/rules binary
+    cd $curDir
+    echo "Debian package created in $dpkgPath"
+    if [ "$installFlag" == 1 ]; then
+	echo "Installing Debian package"
+        dpkg --install "$dpkgPath/$dpkgName"
+    fi 
+    exit 0
+}
+
+function install()
+{
+    local kernel="/boot/memdisk"
+
+    if [ -z $title ]; then
+        title=`basename $destination`
     fi
 
-    if [ "$dest_specified" == 0 ]; then
+    if [ `dirname $destination` != "/boot" ]; then
+        cp -f $destination /boot
+        destination=/boot/`basename $destination`
+    fi
+    $blconf --title=$title --add-kernel=$kernel --add-initrd=$destination
+    echo "Copied image to $destination and updated bootloader"
+
+}
+
+function uninstall()
+{
+
+    $blconf --remove-image=`basename $destination`
+    if [ `dirname $destination` != "/boot" ]; then
+        destination=/boot/`dirname $destination`
         rm -f $destination
     fi
 
-    if [ "$install_flag" == 1 ]; then
-        rpm -ivh $rpm_basedir/RPMS/noarch/$pkg_name-$pkg_version-$pkg_release.noarch.rpm
+}
+
+function makeRpm()
+{
+    # Create base structure
+    mkdir -p $rpmBaseDir
+    mkdir -p $rpmBaseDir/BUILD
+    mkdir -p $rpmBaseDir/SOURCES
+    mkdir -p $rpmBaseDir/SPECS
+    mkdir -p $rpmBaseDir/RPMS/noarch
+    mkdir -p $rpmBaseDir/SRPMS
+
+    if [ "$distro" == "redhat" ]; then
+        specfile="$baseDir/biosdisk-mkrpm-redhat-template.spec"
+    else
+        specfile="$baseDir/biosdisk-mkrpm-generic-template.spec"
+    fi
+        
+    cp -f $destination $rpmBaseDir/SOURCES
+    cp -f $specfile $rpmBaseDir/SPECS
+
+    if [ -z "$pkgName" ]; then
+        pkgName=bios
+    fi
+    if [ -z "$pkgVersion" ]; then
+        pkgVersion=$fileName
+    fi
+    if [ -z "$pkgRelease" ]; then
+        pkgRelease=1
+    fi
+
+    rpmbuild --define "_topdir $rpmBaseDir" --define "name $pkgName" --define "version $pkgVersion" --define "release $pkgRelease" --define "destination $destination" -ba $rpmBaseDir/SPECS/`basename $specfile` >/dev/null 2>&1
+
+    if [ "$?" -eq 0 ]; then
+        echo $""
+        echo $"Created $pkgName-$pkgVersion-$pkgRelease.noarch.rpm in $rpmBaseDir/RPMS/noarch/"
+        echo $""
+        echo $"biosdisk: mkrpm Completed."
+    else
+        echo $"Error: There was a problem creating your rpm."
+        exit 7
+    fi
+
+    if [ "$destSpecifiedFlag" == 0 ]; then
+        rm -f $destination
+    fi
+
+    if [ "$installFlag" == 1 ]; then
+        rpm -ivh $rpmBaseDir/RPMS/noarch/$pkgName-$pkgVersion-$pkgRelease.noarch.rpm
     fi 
 }
 
 # see if we can figure out which distro we're running on
-function find_distro()
+# only rudimentary check for Debian, further checks are in makeDpkg
+function findDistro()
 {
-    if [ -f /etc/fedora-release ] || [ -f /etc/redhat-release ]; then
+    if [ -f /etc/mandrake-release ] || [ "$distro" == "mandrake" ]; then
+        distro=mandrake
+        [ -z $pkgType ] && pkgType=rpm
+    elif [ -f /etc/fedora-release ] || [ -f /etc/redhat-release ] || [ "$distro" == "redhat" ] ; then
         distro=redhat
-    elif [ -f /etc/SuSE-release ]; then
+        [ -z $pkgType ] && pkgType=rpm
+    elif [ -f /etc/SuSE-release ] || [ -f /etc/SuSEconfig ] || [ "$distro" == "suse" ] ; then
         distro=suse
-    elif [ -f /etc/gentoo-release ]; then
+        [ -z $pkgType ] && pkgType=rpm
+    elif [ -f /etc/gentoo-release ] || [ "$distro" == "gentoo" ] ; then
         distro=gentoo
+        [ -z $pkgType ] && pkgType=emerge
+    elif [ -f /etc/debian_version ] || [ "$distro" == "debian" ] ; then
+        distro=debian
+        [ -z $pkgType ] && pkgType=deb
     else
-        echo "Error: Linux distro unknown. mkpkg can't create package"
-        exit 1
+        if [ -z $pkgType ]; then
+            echo "Linux distribution unknown. Please specify the package type with the --pkgtype option on the command line"
+             exit 1
+        fi
     fi
 }
 
@@ -183,37 +285,46 @@ if [ `id -u` != 0 ]; then
 fi
 
 if [ $# -eq 0 ]; then
-    show_usage
+    showUsage
     exit 1
 fi   
 
 eval last=\${$#}
-eval slast=\$`expr $# - 1`
-case $slast in
+eval sLast=\$`expr $# - 1`
+# Catches incomplete switches
+case $sLast in
     -[a-z])
         echo "Error: You do not seem to have specified a BiosExe"
-        show_usage
+        showUsage
         exit 1
         ;;
+
 esac
 
 
 # find biosdisk action
 case $1 in
-    mkfloppy)
-        make_image_flag=1
-        make_floppy_flag=1
+    mkfloppy|mkFloppy)
+        mkImgFlag=1
+        mkFloppyFlag=1
         ;;
-    mkimage)
-	make_image_flag=1
+    mkimage|mkImage)
+	mkImgFlag=1
         ;;
-    mkpkg)
-        make_image_flag=1
-        make_pkg_flag=1
+    mkpkg|mkPkg)
+        mkImgFlag=1
+        mkPkgFlag=1
+        ;;
+    install)
+        mkImgFlag=1
+        installFlag=1
+        ;;
+    uninstall)
+        uninstallFlag=1
         ;;
     *)
         echo "Error: biosdisk action incorrect or not specified"
-        show_usage
+        showUsage
         exit 2
         ;;
 esac
@@ -233,15 +344,15 @@ while [ $# -gt 0 ]; do
                 ;;
             -i) 
                 destination=$2
-                dest_specified=1
+                destSpecifiedFlag=1
                 shift
                 ;;
             -k)
-                dosdisk=$2
+                dosDisk=$2
                 shift
                 ;;
             --install) 
-                install_flag=1
+                installFlag=1
                 ;;
             --distro*)
                 if echo $1 | grep '=' >/dev/null ; then
@@ -253,72 +364,113 @@ while [ $# -gt 0 ]; do
                 ;;
             --name*)
                 if echo $1 | grep '=' >/dev/null ; then
-                    pkg_name=`echo $1 | sed 's/^.*=//'`
+                    pkgName=`echo $1 | sed 's/^.*=//'`
                 else
-                    pkg_name="$2"
+                    pkgName="$2"
                     shift
                 fi
                 ;;
             --version*)
                 if echo $1 | grep '=' >/dev/null ; then
-                    pkg_version=`echo $1 | sed 's/^.*=//'`
+                    pkgVersion=`echo $1 | sed 's/^.*=//'`
                 else
-                    pkg_version="$2"
+                    pkgVersion="$2"
                     shift
                 fi
                 ;;
             --release*)
                 if echo $1 | grep '=' >/dev/null ; then
-                    pkg_release=`echo $1 | sed 's/^.*=//'`
+                    pkgRelease=`echo $1 | sed 's/^.*=//'`
                 else
-                    pkg_release="$2"
+                    pkgRelease="$2"
+                    shift
+                fi
+                ;;
+            --pkgtype*)
+                if echo $1 | grep '=' >/dev/null ; then
+                    pkgType=`echo $1 | sed 's/^.*=//'`
+                else
+                    pkgType="$2"
+                    shift
+                fi
+                ;;
+            --title*)
+                if echo $1 | grep '=' >/dev/null ; then
+                    title=`echo $1 | sed 's/^.*=//'`
+                else
+                    title="$2"
+                    shift
+                fi
+                ;;
+            --bioslog*)
+                if echo $1 | grep '=' >/dev/null ; then
+                    biosChangeLog=`echo $1 | sed 's/^.*=//'`
+                else
+                    biosChangeLog="$2"
                     shift
                 fi
                 ;;
             *)
                 echo "Error: $0 does not take \"$1 $2\" as an option"
-                show_usage
+                showUsage
                 exit 1
 		;;
         esac
     elif [ "$1" -a -z"$2" ]; then
         case $1 in
             -h|--help)
-                show_usage
+                showUsage
                 exit 1
                 ;;
             *)
              # Testing for validity of last argument which should be raw bios or image file
              # If we're here but not on the last argument, the user wrote gibberish
-                if [ $last == $1 ]; then
-                    if [ ! -f $1 ] ; then
+
+               if [ $last == $1 ]; then
+                    if [ ! -f $1 ] && ! [ `echo $1 | grep -c "^[fhFH][tT][Tt]*[pP]"` -eq 1 ]; then
                         echo "Error: \"$1\" treated as a file, but its not useable/nonexistent"
-                        show_usage
+                        showUsage
                         exit 1
                     else
-                        filename=`basename $1 | cut -d. -f1`
-                        file_ext=`basename $1 | cut -d. -f2`
-                        case $file_ext in
+                        #If file is url, then get it
+                        if [ `echo $1 | grep -c "^[fhFH][tT][Tt]*[pP]"` -eq 1 ]; then
+                            file=$libDir/`basename $1`
+			    $wget -O $file $1
+                            if ! [ -f $file ]; then
+                                echo "Error: could not download file!"
+                                exit 1
+                            fi
+                        else
+                            file=$1
+                        fi
+			# In case the download did not work (timeout, programme not found)
+			if [ ! -f $file ]; then
+			    echo "Error: Cannot find/use $file"
+			    exit 1
+			fi
+                        fileName=`basename $file | cut -d. -f1`
+                        fileExt=`basename $file | cut -d. -f2`                 
+                        case $fileExt in
                             img|IMG)
-                                image_complete=1
-                                dest_specified=1
-                                destination=$1
+                                imgCompleteFlag=1
+                                destSpecifiedFlag=1
+                                destination=$file
                                 ;;
                             exe|EXE)
-                                biospath=`dirname $1`
-                                biosfile=$1
-                                biosname=`basename $1`
+                                biosPath=`dirname $file`
+                                biosFile=$file
+                                biosName=`basename $file`
                                 ;;
                             *)
-                                echo "Error: $1 must end in .img or .exe"
-                                show_usage
+                                echo "Error: $file must end in .img or .exe"
+                                showUsage
                                 exit 1
                                 ;;
                             esac 
                     fi
                 else
                     echo "Error: $0 does not take \"$1\" as an option"
-                    show_usage
+                    showUsage
                     exit 1
                 fi
                ;;
@@ -328,23 +480,51 @@ while [ $# -gt 0 ]; do
 done
 
 if [ -z "$destination" ]; then
-    destination=$tmp_location/$filename.img
+    destination=$tmpPath/$fileName.img
 fi
 
-if [ "$make_image_flag" == 1 ] && [ "$image_complete" == 0 ]; then
-    make_image
-fi
-
-if [ "$make_pkg_flag"  == 1 ]; then
-    if [ -z "$distro" ]; then
-        find_distro
+if [ "$uninstallFlag" == 1 ]; then
+    if [ -z $distro ]; then
+        findDistro
     fi
-    case $distro in
-        redhat)
-            make_rpm
+    if [ $pkgType != "deb" ]; then
+    uninstall
+    else
+    	echo "Error: Automatic uninstalls are not supported under $distro"
+        exit 2
+    fi
+fi 
+
+if [ "$mkImgFlag" == 1 ] && [ "$imgCompleteFlag" == 0 ]; then
+    makeImage
+fi
+
+if [ "$installFlag" == 1 ]; then
+    if [ -z $distro ]; then
+        findDistro
+    fi
+    if [ $pkgType != "deb" ]; then
+    install
+    else
+    	echo "Error: Automatic installs are not supported under $distro"
+        exit 2
+    fi
+fi
+
+if [ "$mkPkgFlag"  == 1 ]; then
+    if [ -z "$distro" ] || [ -z "$pkgType" ]; then
+        findDistro
+    fi
+
+    case $pkgType in
+        rpm)
+            makeRpm
+            ;;
+        deb)
+            makeDpkg
             ;;
         *)
-            echo "Error: $distro not supported with mkpkg"
+            echo "Error: $pkgType not supported with mkpkg. Supported package types are: $pkgSupported"
             exit 1
             ;;
     esac    
