Added check to verify that memdisk has been copied to /boot

diff --git a/biosdisk b/biosdisk
--- a/biosdisk
+++ b/biosdisk
@@ -181,6 +181,10 @@ function makeDpkg()
 function install()
 {
     local kernel="/boot/memdisk"
+    if [ ! -f $kernel ]; then
+        echo "Can't find $kernel image"
+        exit 1
+    fi
 
     if [ -z $title ]; then
         title=`basename $destination`
